name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install -g firebase-tools

      # Step 4: Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          SDK_VERSION=491.0.0
          SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          /tmp/google-cloud-sdk/install.sh -q
          source /tmp/google-cloud-sdk/path.bash.inc
          gcloud -v

      # Step 5: Build the React app (budget-pal-client)
      - name: Build React app
        run: npx nx build budget-pal-client --configuration=production

      # Step 6: Build the NestJS app (budget-pal-api)
      - name: Build NestJS app
        run: npx nx build budget-pal-api --configuration=production

      # Step 7: Generate Prisma client for the backend
      - name: Generate Prisma client
        run: npx nx run budget-pal-api:prisma-generate --skip-nx-cache

      # Step 8: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.KEY_FILE_AUTH }} | base64 --decode > /tmp/gcloud-api.json
          gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
          gcloud config set project ${{ secrets.PROJECT_ID }}

      # Step 9: Deploy the backend (budget-pal-api) to Google Cloud Run
      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy budget-pal-api \
            --source dist/apps/budget-pal-api \
            --platform managed \
            --set-env-vars=BUDGET_PAL_DATABASE_URL=${{ secrets.BUDGET_PAL_DATABASE_URL }} \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated

      # Step 10: Deploy the frontend (budget-pal-client) to Firebase Hosting
      - name: Deploy frontend to Firebase Hosting
        run: firebase deploy --only hosting